<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class TermsSeeder extends Seeder
{
    public function run(): void
    {
        $now = Carbon::now();

        $terms = [
            [
                'slug' => 'intro', 'arrangement' => 1,
                'sections_ar' => [['id'=>'intro','type'=>'hero','title'=>'مرحباً بك في منصة وكيلي','content'=>'يسعدنا زيارتك لمنصة "وكيلي". منصة وكيلي هي منصة إلكترونية تهدف إلى تيسير وصول العملاء - أفراداً أو شركات - الراغبين في الحصول على خدمات قانونية إلى المحامين والمستشارين القانونيين بطريقة تفاعلية تحقق مزايا عديدة. تُنظّم هذه الشروط العلاقة الناشئة عن استخدامك للمنصة وتُحدّد الشروط المسموح للمستخدمين بموجبها بالوصول إلى الموقع أو استخدامه.']],
                'sections_en' => [['id'=>'intro','type'=>'hero','title'=>'Welcome to Wakeely Platform','content'=>'We are pleased with your visit to the "Wakeely" platform. Wakeely is an online platform aimed at facilitating access for clients - individuals or companies - seeking legal services to lawyers and legal consultants in an interactive manner that achieves many advantages. These Terms of Use specify the conditions under which users are allowed to access or use the site, and constitute a legally binding agreement between you and Wakeely Platforms LLC.']],
            ],
            [
                'slug' => 'definitions', 'arrangement' => 2,
                'sections_ar' => [['id'=>'definitions','type'=>'definitions','title'=>'التعريفات','items'=>[['term'=>'المنصة / وكيلي','definition'=>'تشير إلى منصة وكيلي و/أو التطبيق والموقع www.wakeely.net وجميع الخدمات التابعة لها وشركة منصات وكيلي المالكة لها.'],['term'=>'المستخدم','definition'=>'هو الشخص الذي يستخدم منصة وكيلي أو يزورها أو يسجّل حساباً عليها أو يقدّم خدمات قانونية من خلالها.'],['term'=>'المحامي','definition'=>'هو أي محامٍ أو مستشار قانوني مسجّل على المنصة، مرخّص من نقابة المحامين بجمهورية مصر العربية أو الجهة الرسمية المانحة للترخيص.'],['term'=>'العميل','definition'=>'هو أي شخص طبيعي أو كيان قانوني يستخدم منصة وكيلي للحصول على الخدمات القانونية.'],['term'=>'الخدمة القانونية','definition'=>'هي أي خدمة قانونية يقدّمها المحامي وفق شروط المنصة، بما في ذلك الاستشارات والمذكرات والقضايا والمرافعات والعقود والتحكيم وغيرها.'],['term'=>'الاتفاقية','definition'=>'تشير إلى هذه الوثيقة التي تشمل الشروط والأحكام والسياسات المختلفة، بما فيها الشروط الخاصة بالمحامين والعملاء وسياسة الخصوصية.']]]],
                'sections_en' => [['id'=>'definitions','type'=>'definitions','title'=>'Definitions','items'=>[['term'=>'The Platform / Wakeely','definition'=>'Refers to the Wakeely platform and/or application and the website www.wakeely.net, all affiliated services, and the owning entity (Wakeely Platforms LLC).'],['term'=>'The User','definition'=>'The person using, visiting, registering on, or providing legal services through the Wakeely platform.'],['term'=>'The Lawyer','definition'=>'Any lawyer or legal consultant registered on the platform, licensed by the Bar Association of the Arab Republic of Egypt or the official licensing authority.'],['term'=>'The Client','definition'=>'Any natural person or legal entity using the Wakeely platform to obtain legal services.'],['term'=>'The Legal Service','definition'=>'Any legal service a lawyer can provide under the platform\'s terms, including consultations, memoranda, cases, pleadings, contracts, arbitration, and other legal activities.'],['term'=>'The Agreement','definition'=>'This document including all terms, conditions, and policies specific to lawyers, clients, and the platform\'s privacy policy.']]]],
            ],
            [
                'slug' => 'services', 'arrangement' => 3,
                'sections_ar' => [['id'=>'services','type'=>'text','title'=>'وصف الخدمات','paragraphs'=>['تعنى منصة وكيلي بربط المحامين من جهة والعملاء من جهة أخرى بطريقة تفاعلية تتيح مزايا عديدة لكلا الطرفين.','تقتصر المنصة على الخدمات القانونية التي يقدّمها محامون مستوفون للشروط المحدّدة في هذه الاتفاقية.','تتيح منصة وكيلي للمحامين التسجيل عبر الضغط على "انضم لشبكة المحامين" أو "انضم كشريك"، كما يمكنهم تحديد التخصصات التي يمتلكون فيها خبرة عملية.']]],
                'sections_en' => [['id'=>'services','type'=>'text','title'=>'Description of Services','paragraphs'=>['Wakeely platform connects lawyers and clients in an interactive manner that provides many advantages for both parties.','The platform is exclusively concerned with legal services provided by lawyers who meet the specific conditions outlined in this agreement.','Wakeely allows lawyers to register by clicking on "Join the Lawyers Network" or "Join as a Partner", and lawyers can specify the specializations in which they have practical experience.']]],
            ],
            [
                'slug' => 'joining-conditions', 'arrangement' => 4,
                'sections_ar' => [['id'=>'joining-conditions','type'=>'list','title'=>'شروط الانضمام للاتفاقية','items'=>['يجب أن يتمتع جميع مستخدمي المنصة بالأهلية القانونية اللازمة لإبرام معاملات ملزمة قانونياً.','يجب أن يكون المستخدم قد بلغ من العمر 18 عاماً على الأقل وقت الانضمام.','يجب على المستخدم قراءة أحكام هذه الاتفاقية كاملةً قبل الانضمام، إذ يُعدّ الانضمام إقراراً بجميع شروطها.','يجب على المستخدم التأكد طوال مدة عضويته من استيفاء جميع الشروط والمتطلبات المحددة في الاتفاقية.','إذا افتقر المستخدم إلى أي شرط من شروط هذه الاتفاقية تُعدّ الاتفاقية باطلة بالنسبة له.']]],
                'sections_en' => [['id'=>'joining-conditions','type'=>'list','title'=>'Conditions for Joining the Agreement','items'=>['All platform users must have the legal capacity to enter into legally binding transactions in accordance with applicable laws.','The user must be at least 18 years old at the time of joining this agreement.','The user must fully read the provisions of this agreement before joining, as joining constitutes acknowledgment of all its terms.','The user must ensure throughout their membership that all conditions and requirements specified in the agreement are met.','If the user lacks any condition of this agreement, the agreement will be void for this user.']]],
            ],
            [
                'slug' => 'electronic-contract', 'arrangement' => 5,
                'sections_ar' => [
                    ['id'=>'electronic-contract','type'=>'text','title'=>'العقد الإلكتروني','paragraphs'=>['نظراً لأن جميع الخدمات المقدّمة إلكترونية، فقد استُعيض عن العقود الموقّعة بخط اليد بعقود إلكترونية ضمن إطار قانوني يراعي جميع الأحكام القانونية المعمول بها.','هذه الاتفاقية عقد إلكتروني بين المنصة وجميع مستخدميها، يحل محل جميع الاتفاقيات الشفهية أو الكتابية السابقة.','يخضع هذا العقد للتعديل والتحديث المستمر، وتقع على المستخدم مسؤولية مراجعته بصفة منتظمة.']],
                    ['id'=>'electronic-signature','type'=>'definitions','title'=>'أنواع التوقيع الإلكتروني','items'=>[['term'=>'الموافقة الصريحة','definition'=>'تكون عند تسجيل المستخدم لحسابه أو تقديم خدمات أو طلب الاستفادة منها، وتُعدّ توقيعاً إلكترونياً على هذه الاتفاقية.'],['term'=>'الموافقة الضمنية','definition'=>'تكون عند استخدام المستخدم لخدمات المنصة أو زيارتها أو البقاء عليها لفترات مطوّلة، وهذا النوع من الاستخدام بمثابة توقيع إلكتروني.']]],
                ],
                'sections_en' => [
                    ['id'=>'electronic-contract','type'=>'text','title'=>'Electronic Contract','paragraphs'=>['Since all services provided are electronic, handwritten contracts have been replaced by electronic contracts within a legal framework that takes into account all applicable legal provisions.','This agreement is an electronic contract between the platform and all its users, replacing all previous oral or written agreements.','This electronic contract is subject to continuous modification and updating. The user is responsible for regularly reviewing this agreement.']],
                    ['id'=>'electronic-signature','type'=>'definitions','title'=>'Types of Electronic Signature','items'=>[['term'=>'Express Approval','definition'=>'Approval is explicit when the user registers their account, provides services, or requests to benefit from services on the platform. This constitutes an electronic signature on this agreement.'],['term'=>'Implied Approval','definition'=>'Approval is implied when the user uses the platform\'s services, visits it, or stays on the platform for extended periods. This usage serves as an electronic signature.']]],
                ],
            ],
            [
                'slug' => 'account-registration', 'arrangement' => 6,
                'sections_ar' => [
                    ['id'=>'account-registration-data','type'=>'text','title'=>'شروط تسجيل الحساب','paragraphs'=>['يستلزم تسجيل حساب المحامي تزويدنا بـ: (الاسم، البريد الإلكتروني، رقم الهاتف المحمول، العنوان، درجة القيد، رقم القيد، تاريخ القيد).','يستلزم تسجيل حساب العميل تزويدنا بـ: (الاسم، البريد الإلكتروني، رقم الهاتف المحمول، العنوان).']],
                    ['id'=>'account-registration-rules','type'=>'list','title'=>'قواعد الحساب','items'=>['يجب أن يتطابق اسم الحساب مع البيانات الرسمية، ويُحظر التسجيل بأسماء مزيّفة أو مضلّلة.','يجب أن تكون صورة الحساب صورة المستخدم الشخصية، ويُحظر رفع صور تخص الآخرين.','يجب التسجيل برقم هاتف وبريد إلكتروني خاصين بالمستخدم.','يُحظر التسجيل بأكثر من حساب واحد، وسيتم حذف جميع الحسابات عند الاكتشاف.','يجب الحفاظ على سرية اسم المستخدم وكلمة المرور، والمستخدم ملتزم بجميع المعاملات عبر حسابه.','نعتبر الحساب ترخيصاً للاستخدام ويحق لنا سحبه في أي وقت دون إبداء أسباب.']],
                ],
                'sections_en' => [
                    ['id'=>'account-registration-data','type'=>'text','title'=>'Account Registration Terms','paragraphs'=>['Registering a lawyer account requires providing: (name, email, mobile phone number, address, registration degree, registration number, registration date).','Registering a client account requires providing: (name, email, mobile phone number, address).']],
                    ['id'=>'account-registration-rules','type'=>'list','title'=>'Account Rules','items'=>['The account name must correspond to official data. Registering with fake or misleading names is prohibited.','The account image must be the user\'s own photo. Uploading images belonging to others is prohibited.','Users must register with their own mobile phone number and email.','Any user is prohibited from registering more than one account; all accounts will be deleted if discovered.','Users must maintain their username and password confidentially and are responsible for all transactions through their account.','We consider the user\'s account a usage license and reserve the right to revoke it at any time without giving reasons.']],
                ],
            ],
            [
                'slug' => 'legal-services-policy', 'arrangement' => 7,
                'sections_ar' => [['id'=>'legal-services-policy','type'=>'text','title'=>'سياسة الخدمات القانونية','paragraphs'=>['تُقدَّم الخدمات القانونية بشكل كامل للعملاء من قِبَل المحامين؛ يوضّح العميل جميع متطلبات الخدمة بشكل واضح عبر الضغط على "نشر مشروع" واتباع الخطوات.','بعد نشر المشروع، تراجع المنصة المشروع، وإن استوفى شروط النشر يُنشر للمحامين في مجال التخصص المطلوب.','يتلقّى العميل عروض أسعار من المحامين المهتمين، وتُحدَّد أسعار الخدمة من قِبَل المحامي حصراً ولا تتدخل المنصة في ذلك.','يُحظر أي تواصل خارجي بين الطرفين، ويقتصر التواصل على منصة وكيلي حصراً.','يُغلق الطلب عند اكتمال تنفيذه من قِبَل المحامي، وأي خدمة جديدة تستلزم فتح طلب جديد.']]],
                'sections_en' => [['id'=>'legal-services-policy','type'=>'text','title'=>'Legal Services Policy','paragraphs'=>['Legal services are provided in full to clients by lawyers. The client clarifies all requirements by clicking on "Publish Project" and following the steps.','After publishing, the platform reviews the project. If it qualifies, it is published for lawyers in the required specialization.','The client receives price offers from interested lawyers. Prices are determined solely by the lawyer; the platform does not intervene.','External communication is strictly prohibited; communication between parties is limited to within the platform only.','The request is closed upon complete execution by the lawyer. For a new service, the client must open a new request.']]],
            ],
            [
                'slug' => 'lawyer-terms', 'arrangement' => 8,
                'sections_ar' => [['id'=>'lawyer-terms','type'=>'list','title'=>'الشروط والأحكام الخاصة بالمحامين','items'=>['يجب أن يكون المحامي مرخّصاً قانونياً، ويقتصر استخدامه للمنصة على مدة سريان ترخيصه.','يجب تقديم جميع الأدلة المطلوبة: نسخة من بطاقة عضوية نقابة المحامين، نسخة من بطاقة الهوية، المؤهلات والخبرات.','يجب تقديم الخدمات بصدق وأمانة. يُحظر الغش والتضليل، وعند الإثبات يُوقف الحساب.','يجب الشرح الكامل للعميل عن الخدمة المقدَّمة وخطوات تنفيذها.','يجب الالتزام بالسعر المُقدَّم في العرض، ويُحظر تغييره بعد قبول العميل.','يجب تقديم الخدمة شخصياً، ويُحظر تفويض الغير في تقديمها.','يجب تقديم الخدمة بشكل إبداعي، ويُحظر النسخ واللصق من محتوى الآخرين.','إذا عجز المحامي عن تقديم الخدمة يجب الاعتذار بأسلوب لائق.','يضمن المحامي الخدمات القانونية المقدَّمة وللعميل الحق في الرجوع عليه عند العيب.','يجب معاملة العميل بالاحترام الواجب، ويُحظر توجيه أي إساءة إليه.','المحامي مسؤول شخصياً عن جميع الأخطاء العمدية وغير العمدية أثناء تقديم الخدمة.']]],
                'sections_en' => [['id'=>'lawyer-terms','type'=>'list','title'=>'Terms and Conditions Specific to Lawyers','items'=>['The lawyer must be legally authorized to provide services. Use of the platform is limited to the validity period of their license.','The lawyer must provide all required evidence: Bar Association membership card, national ID, qualifications, and experience.','The lawyer must provide legal services honestly. Deception or misleading the client is prohibited; if proven, the account will be banned.','The lawyer must fully explain what they will provide to the client.','The lawyer must strictly adhere to the price offered in the proposal. Changing prices after client acceptance is prohibited.','The lawyer must provide the service personally. Delegating to others is prohibited.','The lawyer must provide services creatively; using copy-paste from others\' content is prohibited.','If unable to provide the agreed service, the lawyer must politely apologize.','The lawyer guarantees the legal services provided; the client has the right to recourse for faulty service.','The lawyer must treat the client with proper respect; directing any abuse is prohibited.','The lawyer is personally responsible for all intentional and unintentional errors committed while providing the service.']]],
            ],
            [
                'slug' => 'quality-standards', 'arrangement' => 9,
                'sections_ar' => [
                    ['id'=>'quality-intro','type'=>'text','title'=>'معايير ضمان جودة الخدمات القانونية','paragraphs'=>['تلتزم منصة "وكيلي" بضمان حصول العميل على أفضل تجربة في الحصول على خدمات قانونية متميزة وعالية الجودة. يجب على كل محامٍ مسجَّل الالتزام بالمعايير التالية:']],
                    ['id'=>'quality-list','type'=>'list','title'=>'المعايير المطلوبة','items'=>['الالتزام بقواعد السلوك والمبادئ الأخلاقية لمهنة المحاماة.','الحفاظ على التواصل الواضح وفي الوقت المناسب مع العميل.','الرد السريع والمهني على استفسارات العميل.','الحفاظ على السرية التامة فيما يخص معلومات العميل وتفاصيل مشروعه.','امتلاك الخبرة والمؤهلات اللازمة في التخصص القانوني المختار.','تقديم تقييمات دقيقة وشاملة للمشاريع القانونية.','عرض الرسوم وأي تكاليف إضافية محتملة بوضوح.','تحديث العميل بانتظام حول تقدّم مشروعه بما في ذلك أي تحديات أو تأخيرات.','إطلاع العميل على الخيارات القانونية المتاحة بما فيها المخاطر والفوائد.','شرح الاستراتيجيات القانونية والنتائج المحتملة بلغة يفهمها العميل.','معالجة شكاوى العميل بسرعة واحترافية.','تجنّب تضارب المصالح والإفصاح عن أي تعارضات للعميل.','اتخاذ جميع الإجراءات اللازمة لتأمين البيانات وحماية معلومات العميل.','تشجيع العميل على تقديم ملاحظاته حول الخدمات المقدَّمة.']],
                ],
                'sections_en' => [
                    ['id'=>'quality-intro','type'=>'text','title'=>'Quality Assurance Standards for Legal Services','paragraphs'=>['Wakeely is committed to ensuring clients receive the best experience in obtaining distinguished and high-quality legal services. Every registered lawyer must adhere to the following standards:']],
                    ['id'=>'quality-list','type'=>'list','title'=>'Required Standards','items'=>['Adherence to the code of conduct and ethical principles of the legal profession.','Maintaining clear and timely communication with the client.','Prompt and professional response to client inquiries.','Maintaining complete confidentiality regarding client information and legal project details.','Having the necessary experience and qualifications in the chosen legal specialization.','Providing accurate and comprehensive evaluations of legal projects.','Clearly displaying fees and any possible additional costs.','Regularly updating the client on legal project progress, including challenges or delays.','Informing the client of different legal options, including risks and potential benefits.','Clearly explaining legal strategies and potential outcomes in understandable language.','Handling client complaints promptly and professionally.','Avoiding conflicts of interest and disclosing any potential conflicts to the client.','Taking all necessary measures to secure data and protect client information.','Encouraging clients to provide feedback on legal services provided.']],
                ],
            ],
            [
                'slug' => 'client-terms', 'arrangement' => 10,
                'sections_ar' => [['id'=>'client-terms','type'=>'list','title'=>'الشروط والأحكام الخاصة بالعملاء','items'=>['يجب على العميل تسجيل حساب على المنصة ليتمكن من نشر مشروع يتضمن الخدمة القانونية المطلوبة.','يتحمل العميل المسؤولية الكاملة عن جميع المشاريع المقدَّمة وجميع المدفوعات المنفَّذة عبر حسابه.','الاستخدام شخصي حصراً، ويُحظر تفويض الآخرين أو الإفصاح عن بيانات الحساب.','إذا كان العميل شركة أو مؤسسة، يجب أن تتم عمليات التسجيل من قِبَل الممثل القانوني أو من يفوّضه.','يجب تحديد الخدمة القانونية المطلوبة بوضوح. في حالة النشر الخاطئ وتقديم المحامي الخدمة كما اتُّفق، لا يحق للعميل تغيير المشروع.','طبيعة التزام المحامي "تحقيق نتيجة" في المسائل التي تحسمها القوانين، و"بذل عناية" في المسائل التقديرية.','المحامي هو المسؤول الوحيد عن الخدمات القانونية المقدَّمة، ودور المنصة يقتصر على الربط بين الأطراف.','لا يحق للعميل الاعتراض على الخدمة أو إلغاؤها إذا قدّمها المحامي كما اتُّفق عليه.','يوافق العميل على معاملة المحامي بالاحترام الواجب، ويُحظر توجيه أي إساءة إليه.','تضمن منصة وكيلي المدفوعات المنفَّذة عبر المنصة فحسب، ولا تضمن أي مدفوعات خارجها.']]],
                'sections_en' => [['id'=>'client-terms','type'=>'list','title'=>'Terms and Conditions for Clients','items'=>['The client must register an account to post a project containing the required legal service.','The client is fully responsible for all projects submitted and all payments made through their account.','Account use is strictly personal; authorizing others or disclosing account credentials is prohibited.','If the client is a company or institution, registration must be carried out by the legal representative or their authorized delegate.','The client must clearly specify the required legal service. If incorrectly posted and the lawyer provides the service as agreed, the client cannot change the project.','The lawyer\'s obligation is to "achieve a result" in matters settled by law, and to "exercise care" in discretionary matters.','The lawyer is solely responsible for legal services provided; the platform\'s role is only to connect the parties.','The client has no right to object to or cancel the service if it has been fully executed as agreed.','The client agrees to treat the lawyer with proper respect; directing any abuse is prohibited.','Wakeely only guarantees payments made through the platform; payments outside the platform are not guaranteed.']]],
            ],
            [
                'slug' => 'dispute-resolution', 'arrangement' => 11,
                'sections_ar' => [
                    ['id'=>'dispute-intro','type'=>'text','title'=>'آلية حل النزاعات بين العميل والمحامي','paragraphs'=>['يُعدّ وضع معايير واضحة لحل أي نزاعات قد تنشأ بين المحامين والعملاء من أهم أولوياتنا للحفاظ على الثقة وضمان استدامة تقديم الخدمات بجودة عالية.']],
                    ['id'=>'dispute-steps','type'=>'grouped-list','title'=>'إجراءات التعامل مع الشكاوى','groups'=>[['title'=>'أولاً: شروط قبول الشكوى','items'=>['وجود مستندات تدعم ادعاء مقدّم الشكوى، إذ لا نعتمد على الأقوال المجردة.','يجب أن تكون جميع المحادثات قد جرت داخل فضاء المحادثة المتاح على الموقع.']],['title'=>'ثانياً: إجراءات تسجيل الشكوى','items'=>['التواصل عبر البريد الإلكتروني shakwa@wakeely.net مع شرح مفصّل والمستندات الداعمة.','يتحقق فريقنا من شروط قبول الشكوى خلال 48 ساعة من استلامها.','في حال قبول الشكوى، يتواصل فريقنا مع الطرف المُشكى منه.','يعمل فريقنا على التوفيق بين وجهات النظر والوصول إلى حل مُرضٍ.','في حال تعذّر الحل، يُدعى الطرفان إلى اجتماع في مقر الشركة مع المستشار القانوني.','عند وجود خطأ واضح ولم يُحل النزاع، يحق لمنصة وكيلي اتخاذ الإجراء المناسب.']],['title'=>'ثالثاً: العقوبات','items'=>['للعميل: التحذير والإنذار — الحظر من شهر إلى ستة أشهر — شطب التسجيل.','للمحامين: التحذير والإنذار — تقييد امتيازات الاشتراك — الحظر من شهر إلى ستة أشهر — شطب التسجيل.']]]],
                ],
                'sections_en' => [
                    ['id'=>'dispute-intro','type'=>'text','title'=>'Mechanism for Resolving Disputes Between Client and Lawyer','paragraphs'=>['Establishing clear standards for resolving disputes between lawyers and clients is of utmost importance to maintain trust and ensure the sustainability of high-quality services.']],
                    ['id'=>'dispute-steps','type'=>'grouped-list','title'=>'Complaint Handling Procedures','groups'=>[['title'=>'First: Conditions for Accepting the Complaint','items'=>['Existence of documents supporting the complainant\'s claim; unsupported statements are not relied upon.','All conversations and agreements must have taken place within the platform\'s chat space.']],['title'=>'Second: Complaint Registration Procedures','items'=>['Contact us via shakwa@wakeely.net with a detailed explanation and supporting documents.','Our team verifies the complaint conditions and validity within 48 hours of receipt.','If accepted, our team contacts the party against whom the complaint is made.','Our team works to reconcile viewpoints and reach a satisfactory solution for both parties.','If the dispute cannot be resolved, both parties are invited to a meeting at company headquarters.','If there is a clear error and the dispute remains unresolved, Wakeely has the right to take appropriate action.']],['title'=>'Third: Penalties','items'=>['For the client: Warning and notice — Prohibition for one to six months — De-registration.','For lawyers: Warning and notice — Restriction of subscription privileges — Prohibition for one to six months — De-registration.']]]],
                ],
            ],
            [
                'slug' => 'confidentiality-privacy', 'arrangement' => 12,
                'sections_ar' => [
                    ['id'=>'confidentiality','type'=>'text','title'=>'الالتزام بالسرية المهنية','paragraphs'=>['يتعهّد المحامي بالحفاظ على جميع البيانات والمعلومات والملفات التي يطّلع عليها أثناء تقديم الخدمات ولا يجوز الإفصاح عنها لأي شخص أو جهة.','يتعهّد المحامي بعدم إضافة الخدمات التي يؤدّيها للعميل إلى ملف أعماله دون موافقة خطية من العميل.','أي مخالفة لهذه الأحكام تُعدّ انتهاكاً للالتزام بالسرية، ويتحمّل المحامي المسؤولية القانونية الكاملة.']],
                    ['id'=>'privacy','type'=>'text','title'=>'سياسة الخصوصية والأمان','paragraphs'=>['نؤمن بأن خصوصية معلوماتك تُعدّ من أهم جوانب علاقتنا بك، ونلتزم بالحفاظ على سريتها وأمنها.','سنخطرك فوراً في حال حدوث اختراق قد يُعرّض خصوصية معلوماتك للخطر.','لن نستخدم معلوماتك أو نشاركها إلا كما هو موضّح هنا. أنت المالك الوحيد لبياناتك.']],
                ],
                'sections_en' => [
                    ['id'=>'confidentiality','type'=>'text','title'=>'Professional Confidentiality Commitment','paragraphs'=>['The lawyer undertakes to preserve and protect all data, information, and files accessed while providing legal services. Disclosure to any other person or entity is not permissible.','The lawyer undertakes not to add legal services performed for the client to their portfolio without the client\'s written consent.','Any violation of these provisions is deemed a breach of confidentiality obligations, making the lawyer legally responsible.']],
                    ['id'=>'privacy','type'=>'text','title'=>'Privacy and Security Policy','paragraphs'=>['We believe that the privacy of your information is one of the most important aspects of our relationship with you, and we are legally obligated to maintain its security.','We will immediately inform you in the event of a breach that may compromise the privacy or security of your information.','We will not use or share your information except as outlined here. You are the sole owner of your data.']],
                ],
            ],
            [
                'slug' => 'payment-policy', 'arrangement' => 13,
                'sections_ar' => [
                    ['id'=>'payment-clients','type'=>'numbered-list','title'=>'سياسة الدفع للعملاء','items'=>['استخدام المنصة من قِبَل العميل مجاني؛ يتحمّل العميل المدفوعات الخاصة بالخدمات القانونية.','العملة الرسمية المقبولة هي الجنيه المصري، وقد يُتاح الدفع بعملة أو أكثر وفق سياسة المنصة.','توفّر المنصة بوابة دفع إلكتروني بالتعاون مع مزوّد خدمة دفع لتوفير تجربة دفع سهلة وآمنة.','قد تفرض البنوك ومزوّد خدمة الدفع رسوماً على التحويل أو الردّ، ويتحمّل العميل كافة هذه الرسوم.','تحتفظ المنصة بالحق في تعديل سياسة الدفع في أي وقت دون الحاجة إلى موافقة المستخدم.']],
                    ['id'=>'payment-lawyers','type'=>'numbered-list','title'=>'سياسة الدفع للمحامين','items'=>['الخدمات التي تقدمها المنصة غير مجانية للمحامين، ويمكن استخدامها مقابل الاشتراك في إحدى الباقات المُعلنة.','قد تُقدّم المنصة عروضاً خاصة تُعفي المحامي من الاشتراك لمدة تحدّدها المنصة.','في حال سداد أتعاب المحامي عبر خدمة التمويل، تستحق منصة وكيلي عمولة 15% تُخصم مباشرةً.','تُحوَّل مستحقات المحامي خلال 15 يوماً من تاريخ طلبه تحويل الأموال.']],
                ],
                'sections_en' => [
                    ['id'=>'payment-clients','type'=>'numbered-list','title'=>'Payment Policy for Clients','items'=>['Use of the platform by the client is free; the client bears the payments for legal services requested from the lawyer.','The official currency accepted is the Egyptian Pound; payment may be provided in one or more currencies according to the platform\'s policy.','The platform provides an electronic payment gateway in cooperation with a payment service provider for an easy and secure payment experience.','Banks and the payment service provider may impose fees on transfers or refunds; the client is responsible for all such fees.','The platform reserves the right to modify its payment policy at any time without requiring user consent.']],
                    ['id'=>'payment-lawyers','type'=>'numbered-list','title'=>'Payment Policy for Lawyers','items'=>['Platform services are not free for lawyers; the lawyer can use the platform in exchange for subscribing to one of the announced packages.','The platform may provide special offers exempting the lawyer from subscription for a period it determines.','If the client pays through the financing service, Wakeely is entitled to a commission of 15% of the amount due, deducted directly.','The platform transfers the lawyer\'s dues within 15 days from the date of the lawyer\'s transfer request.']],
                ],
            ],
            [
                'slug' => 'intellectual-property', 'arrangement' => 14,
                'sections_ar' => [['id'=>'intellectual-property','type'=>'text','title'=>'حقوق الملكية الفكرية والعلامات التجارية','paragraphs'=>['المنصة بجميع عناصرها مملوكة لنا ملكية خاصة، ولا يجوز محاكاتها أو نسخها أو إعادة استخدامها بأي شكل.','جميع المحتويات على المنصة محمية قانونياً وفق القوانين المعمول بها والاتفاقيات الدولية.','"وكيلي" علامة تجارية مسجّلة لا يجوز المساس بها أو استخدامها بصورة غير مشروعة.','قد تتوفر عبر المنصة علامات تجارية لأطراف ثالثة، وفي حالة الاعتداء عليها يحق لأصحابها اتخاذ الإجراءات القانونية.']]],
                'sections_en' => [['id'=>'intellectual-property','type'=>'text','title'=>'Intellectual Property Rights & Trademarks','paragraphs'=>['The platform and all its elements are privately owned by us and may not be imitated, copied, or reused in any form.','All content on the platform is subject to legal protection under applicable laws and international agreements.','"Wakeely" is a registered trademark that may not be infringed upon, imitated, or illegally used.','Third-party trademarks may be available through the platform; in case of infringement, the trademark owners have the right to take legal action.']]],
            ],
            [
                'slug' => 'liability', 'arrangement' => 15,
                'sections_ar' => [['id'=>'liability','type'=>'text','title'=>'المسؤولية القانونية وإخلاء المسؤولية والتعويضات','paragraphs'=>['كل مستخدم مسؤول شخصياً عن جميع الأفعال التي تتم عبر المنصة، ولن تتحمل منصة وكيلي أي مسؤولية تضامنية.','تبرأ ذمة المنصة من جميع الأنشطة غير المشروعة غير المتعلقة بها والتي قد تحدث عبرها.','لا تتحمل المنصة المسؤولية عن أي خسائر أو أضرار مباشرة أو غير مباشرة أو خاصة أو تبعية.','لا تقدّم منصة وكيلي أي نوع من التأمين أو التعويضات لأي من مستخدميها.','يتعهّد المستخدم بتعويضنا كاملاً عن جميع الأضرار الناجمة عن أفعاله غير المشروعة أو عدم امتثاله لشروط المنصة.']]],
                'sections_en' => [['id'=>'liability','type'=>'text','title'=>'Legal Responsibility, Disclaimer & Indemnities','paragraphs'=>['Each user is personally responsible for all actions carried out through the platform. Wakeely will not be jointly or vicariously liable for any of the users.','The platform disclaims all responsibility for illegal activities unrelated to it that may occur through the platform.','The platform is not responsible for any damages incurred, including direct, indirect, special, consequential, or incidental damages.','Wakeely does not provide any type of insurance or compensation for any of its users.','The user undertakes to fully compensate us for all damages arising from unlawful acts or failure to comply with the platform\'s terms.']]],
            ],
            [
                'slug' => 'governing-law', 'arrangement' => 16,
                'sections_ar' => [['id'=>'governing-law','type'=>'text','title'=>'القانون الواجب التطبيق والاختصاص القضائي','paragraphs'=>['يخضع تفسير وتنفيذ هذه الوثيقة للقوانين المعمول بها في جمهورية مصر العربية.','ينعقد الاختصاص للقضاء المصري للفصل في أي نزاع ينشأ عن تفسير أو تنفيذ أي حكم من أحكام هذه الوثيقة.','تُحرَّر هذه الوثيقة باللغة العربية، وفي حال ترجمتها يسود النص العربي عند أي تعارض مع الترجمة.']]],
                'sections_en' => [['id'=>'governing-law','type'=>'text','title'=>'Governing Law & Jurisdiction','paragraphs'=>['The interpretation and implementation of the provisions of this document are subject to the laws applicable in the Arab Republic of Egypt.','The Egyptian judiciary has jurisdiction to adjudicate any dispute arising from the interpretation or implementation of any provision of this document.','This document is drafted in the Arabic language. In the event of translation, the Arabic text shall prevail if the foreign translation conflicts with it.']]],
            ],
        ];

        foreach ($terms as $term) {
            DB::table('terms')->updateOrInsert(
                ['slug' => $term['slug']],
                [
                    'slug'        => $term['slug'],
                    'sections_ar' => json_encode($term['sections_ar'], JSON_UNESCAPED_UNICODE),
                    'sections_en' => json_encode($term['sections_en'], JSON_UNESCAPED_UNICODE),
                    'arrangement' => $term['arrangement'],
                    'created_at'  => $now,
                    'updated_at'  => $now,
                ]
            );
        }
    }
}